import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./ui/globals.css";

const rubikFont = Rubik({
  variable: "--font-rubik", // Asegúrate de crear una variable para la fuente Rubik
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/Svg/DataSamLogo.svg",  // Ruta del ícono en la carpeta 'public'
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Puedes agregar más elementos meta aquí */}
        <title>DATA SAM</title>
        <link rel="icon" href="/Svg/DataSamLogo.svg" />
      </head>
      <body className={`${rubikFont.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
